### ISSUE TITLE
Wrapping a function in native folder to a Java 

### ISSUE THREAD

**Issue by tha061** [lubux/ecelgamal#1]
Hi author,
Thank you very much for sharing this repository. I am following this library to implement my application using ECElgama cryptosystem. This works very well with all functions you have developed.

I am currently developing a re-encryption function in the native folder and wish to call it from Java. I wrote a wrapper in crtecelgamal_jni_wrapper.c to wrap my "re-encrypt" function in the ecelgamal.c and then build it from native. Then I compile the jar package using "mvn package". I tried to call the re-encrypt function in java but I could not make it.

Could you please give me more details on how to wrap a function in the native folder and use it in java folder? 

I am look forward to hearing from you soon.

Thank you

**Comment by lubux** [comment]
Hi, check [crtecelgamal_jni_wrapper.c](https://github.com/lubux/ecelgamal/blob/master/native/crtecelgamal_jni_wrapper.c) and the respective java class [ECElGamal.java (native)](https://github.com/lubux/ecelgamal/blob/master/src/main/java/ch/ethz/dsg/ecelgamal/ECElGamal.java).

Use the `compile-and-install.sh` script, which builds the libraries and copies them into the right folder in `src/main/resources/META-INF/lib`

**Comment by tha061** [comment]
Hi Lukas,

Thank you for you response.

I have followed your suggestions.
For an exercise of how to wrap a c function to java, I tried to wrap function "gamal_encrypt( )" to "encryptth( )" in  crtecelgamal_jni_wrapper.c<https://github.com/lubux/ecelgamal/blob/master/native/crtecelgamal_jni_wrapper.c> which is just the same as your "encrypt( )" function.

jbyteArray Java_ch_ethz_dsg_ecelgamal_ECElGamal_encryptth(JNIEnv *env,
                                        jobject javaThis, jlong value,
                                        jbyteArray key_oct) {
    gamal_key_t key;
    gamal_ciphertext_t ciphertext;
    unsigned char *buffer;
    size_t cipher_size;
    jbyteArray res;

    get_key(env, key, key_oct);
    gamal_encrypt(ciphertext, key, (dig_t) value);

    cipher_size = get_encoded_ciphertext_size(ciphertext);
    buffer = (unsigned char *) malloc(cipher_size);
    encode_ciphertext(buffer, (int) cipher_size, ciphertext);
    res = as_byte_array(env, buffer, (int) cipher_size);

    free(buffer);
    gamal_key_clear(key);
    gamal_cipher_clear(ciphertext);
    return res;
}

Then I run "make" in the native library.
The make was successful:

Scanning dependencies of target ecelgamal-jni-wrapper
[  5%] Building C object CMakeFiles/ecelgamal-jni-wrapper.dir/crtecelgamal_jni_wrapper.c.o
[ 11%] Linking C shared library out/libecelgamal-jni-wrapper.so
[ 16%] Built target ecelgamal-jni-wrapper
[ 83%] Built target ecelgamal
[100%] Built target ecelgamal-lib


Then I implemented a function in ECElGamal.java <https://github.com/lubux/ecelgamal/blob/master/src/main/java/ch/ethz/dsg/ecelgamal/ECElGamal.java> which uses the wrapped function "encryptth( )":

public static ECElGamalCiphertext encrypt_th(BigInteger integer, ECElGamalKey key) {
        byte[][] ciphertexts = new byte[key.params.ds.length][];
        for(int iter=0; iter<ciphertexts.length; iter++) {
            BigInteger mi = integer.mod(key.getParams().ds[iter]);
            ciphertexts[iter] = encryptth(mi.longValue(), key.keyContent);
        }
        return new ECElGamalCiphertext(ciphertexts);
    }

However, when I called this function (encrypt_th) in my main app, I got the errors as below, though there is no error if I used your "encrypt()":

Exception in thread "main" java.lang.UnsatisfiedLinkError: 'byte[] ch.ethz.dsg.ecelgamal.ECElGamal.encryptth(long, byte[])'
at ch.ethz.dsg.ecelgamal.ECElGamal.encryptth(Native Method)
at ch.ethz.dsg.ecelgamal.ECElGamal.encrypt_th(ECElGamal.java:172)
at com.dataring.App.main(App.java:28)

Do you have any idea what was the problem?

Thank you for your time,

Best regards
Tham


________________________________

**Comment by lubux** [comment]
After make, have you moved the libraries from `./native/out` to `./src/main/resources/META-INF/lib/<your_OS>`?

**Comment by tha061** [comment]
Hi Lukas,
Thank you for your response.

Do you mean I should manually move (or copy) the .so files in ./native/out to ./src/main/resources/META-INF/lib/linux64 (my OS)?

I just run the command “mvn package” to update the .jar file.

Best regards
Tham


On 6 Feb 2020, at 7:53 pm, Lukas Burkhalter <notifications@github.com<mailto:notifications@github.com>> wrote:


After make, have you moved the libraries from ./native/out to ./src/main/resources/META-INF/lib/<your_OS>?

**Comment by lubux** [comment]
yes or run the [script](https://github.com/lubux/ecelgamal/blob/master/native/compile-and-install.sh)
